import type { Product } from './database.types'

const now = new Date().toISOString()

function product(overrides: Partial<Product>): Product {
  return {
    id: overrides.id || crypto.randomUUID?.() || Math.random().toString(36).slice(2),
    name: 'Wingxtra Product',
    slug: 'wingxtra-product',
    description: 'Curated UAV product for builders and operators.',
    price: 1000,
    sale_price: null,
    sale_label: null,
    fulfillment_type: 'fdm',
    category_id: null,
    category: null,
    brand_id: null,
    brand: 'Wingxtra',
    product_family: 'additive_manufacturing',
    product_origin: 'wingxtra',
    delivery_type: 'digital_download',
    additive_manufacturing_type: 'fdm_printable_files',
    supplier_sku: '',
    warranty_notes: 'Curated and supplied by Wingxtra.',
    compatibility_notes: '',
    image_url: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1200&q=80',
    stl_file_path: '',
    stock_count: 0,
    track_inventory: false,
    inventory_policy: 'made_to_order',
    low_stock_threshold: 3,
    lead_time_days: 0,
    is_active: true,
    weight_grams: 0,
    is_drone_product: false,
    is_recommended_electronic: false,
    is_new_arrival: false,
    tags: [],
    specs: {},
    created_at: now,
    updated_at: now,
    ...overrides,
  }
}

export const fallbackProducts: Product[] = [
  product({
    id: 'demo-scout-vtol',
    name: 'Wingxtra Scout VTOL Core Kit',
    slug: 'wingxtra-scout-vtol-core-kit',
    description: 'Hybrid platform concept kit for builders evaluating VTOL geometry, modular payload bays, and repairable airframe sections.',
    price: 47880,
    sale_price: 39480,
    sale_label: 'Launch price',
    fulfillment_type: 'mjf',
    brand: 'Wingxtra',
    product_family: 'wingxtra_aircraft',
    product_origin: 'wingxtra',
    delivery_type: 'made_to_order',
    additive_manufacturing_type: 'mjf_printed_parts',
    image_url: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1200&q=80',
    stock_count: 4,
    track_inventory: true,
    inventory_policy: 'made_to_order',
    lead_time_days: 7,
    is_drone_product: true,
    is_new_arrival: true,
    tags: ['vtol', 'mjf', 'airframe'],
    specs: {
      wingspan: '1.2 m', payload: '1.5 kg', skill_level: 'Advanced', build_time: 'Workshop build',
      included: ['MJF structural parts', 'Assembly notes', 'Compatibility checklist'],
      requirements: ['Flight controller', 'Motors and ESCs', 'Battery and radio link'],
      overview: 'A modular VTOL-oriented platform concept for serious builders who want a repairable aircraft architecture.',
    },
  }),
  product({
    id: 'demo-fixed-wing-stl',
    name: 'Wingxtra Swift Fixed-Wing STL Pack',
    slug: 'wingxtra-swift-fixed-wing-stl-pack',
    description: 'Digital printable fixed-wing airframe files for builders who want local production and fast replacement parts.',
    price: 7800,
    fulfillment_type: 'fdm',
    product_family: 'additive_manufacturing',
    delivery_type: 'digital_download',
    additive_manufacturing_type: 'stl_digital_files',
    image_url: 'https://images.unsplash.com/photo-1593697821028-7cc59cfd7399?auto=format&fit=crop&w=1200&q=80',
    is_drone_product: true,
    tags: ['stl', 'fixed-wing', 'fdm'],
    specs: { file_formats: 'STL | PDF', wingspan: '980 mm', printer: '220 x 220 mm bed', overview: 'Printable fixed-wing file pack with modular repair sections.' },
  }),
  product({
    id: 'demo-epo-airframe',
    name: 'AeroLite EPO Survey Airframe',
    slug: 'aerolite-epo-survey-airframe',
    description: 'Curated EPO fixed-wing airframe for efficient survey, training, and payload testing missions.',
    price: 12800,
    fulfillment_type: 'composite',
    brand: 'AeroLite',
    product_family: 'fixed_wing_uavs',
    product_origin: 'curated_brand',
    delivery_type: 'physical_shipment',
    image_url: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1200&q=80',
    stock_count: 8,
    track_inventory: true,
    inventory_policy: 'deny',
    tags: ['epo', 'fixed-wing', 'survey'],
    specs: { wingspan: '1600 mm', material: 'EPO foam', ideal_for: 'Training and survey test builds' },
  }),
  product({
    id: 'demo-carbon-boom',
    name: 'Carbon Tail Boom Assembly',
    slug: 'carbon-tail-boom-assembly',
    description: 'Lightweight carbon composite boom for fixed-wing and VTOL builds that need stiffness with low mass.',
    price: 6200,
    fulfillment_type: 'composite',
    brand: 'Wingxtra',
    product_family: 'airframes_kits',
    product_origin: 'wingxtra',
    delivery_type: 'physical_shipment',
    image_url: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?auto=format&fit=crop&w=1200&q=80',
    stock_count: 2,
    low_stock_threshold: 3,
    tags: ['carbon', 'airframe'],
    specs: { material: 'Carbon fiber composite', finish: 'Workshop-ready matte finish' },
  }),
  product({
    id: 'demo-flight-controller',
    name: 'PX4-Class Flight Controller',
    slug: 'px4-class-flight-controller',
    description: 'Curated flight controller for fixed-wing, VTOL, and multirotor UAV platforms.',
    price: 9200,
    fulfillment_type: 'composite',
    brand: 'NavCore',
    product_family: 'avionics_flight_control',
    product_origin: 'curated_brand',
    delivery_type: 'physical_shipment',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    stock_count: 10,
    is_recommended_electronic: true,
    tags: ['flight-controller', 'px4', 'avionics'],
    specs: { best_for: 'Autonomous UAV control and telemetry integration', compatibility: 'PX4 and ArduPilot workflows' },
  }),
  product({
    id: 'demo-brushless-motor',
    name: 'Wingxtra 2814 Brushless Motor',
    slug: 'wingxtra-2814-brushless-motor',
    description: 'Efficient brushless motor for medium fixed-wing and VTOL propulsion systems.',
    price: 4500,
    fulfillment_type: 'composite',
    brand: 'Wingxtra',
    product_family: 'propulsion_systems',
    product_origin: 'wingxtra',
    delivery_type: 'physical_shipment',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    stock_count: 18,
    is_recommended_electronic: true,
    tags: ['motor', 'propulsion'],
    specs: { kv: '900KV', max_current: '38A', best_for: 'Fixed-wing and VTOL propulsion' },
  }),
  product({
    id: 'demo-parachute',
    name: 'Compact UAV Recovery Parachute',
    slug: 'compact-uav-recovery-parachute',
    description: 'Safety recovery parachute for lightweight UAV test programs and higher-risk prototype missions.',
    price: 6900,
    fulfillment_type: 'composite',
    brand: 'SafeAero',
    product_family: 'recovery_safety',
    product_origin: 'partner_brand',
    delivery_type: 'physical_shipment',
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    stock_count: 6,
    tags: ['parachute', 'safety', 'recovery'],
    specs: { max_uav_mass: '8 kg', deployment: 'Servo release or flight-controller trigger' },
  }),
  product({
    id: 'demo-winch',
    name: 'Payload Winch Mission Module',
    slug: 'payload-winch-mission-module',
    description: 'Mission-system winch module for payload lowering tests and specialized UAV applications.',
    price: 18800,
    fulfillment_type: 'composite',
    brand: 'Wingxtra',
    product_family: 'winches_mission_systems',
    product_origin: 'wingxtra',
    delivery_type: 'made_to_order',
    image_url: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1200&q=80',
    stock_count: 0,
    inventory_policy: 'made_to_order',
    lead_time_days: 14,
    tags: ['winch', 'mission-system'],
    specs: { payload: '1 kg test payload', lead_time: 'Ships after mission configuration review' },
  }),
]
